on:
  schedule:
    - cron:  '0,30 * * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        uses: tyrrrz/action-http-request@master
        with:
          url: ${{ vars.CALL_URL }}